import { CACHE_MANAGER } from '@nestjs/cache-manager';
import {
  BadRequestException,
  Inject,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import {
  $Enums,
  AdminAction,
  type Prisma,
  PromotionStatus,
} from '@prisma/client';
import type { Cache } from 'cache-manager';

import { EmailService } from '../email/email.service.js';
import { NotificationsService } from '../notifications/notifications.service.js';
import { PrismaService } from '../prisma/prisma.service.js';
import type { BroadcastEmailDto } from './dto/broadcast-email.dto.js';
import type { UpdateWhitelistEntryDto } from './dto/update-whitelist-entry.dto.js';

const ReportReason = $Enums.ReportReason;
type ReportReason = $Enums.ReportReason;
const ReportStatus = $Enums.ReportStatus;
type ReportStatus = $Enums.ReportStatus;
const NotificationType = $Enums.NotificationType;

/**
 * Custom interface to ensure verification fields are recognized.
 * These should be generated by Prisma, but we cast here to resolve linting issues
 * if the local TS Server is out of sync with node_modules.
 */
type VLevel = 'BASIC' | 'VERIFIED' | 'BUSINESS' | 'ELITE';
type AType = 'PERSONAL' | 'CREATOR' | 'BUSINESS';

interface UserWithVerification
  extends Prisma.UserGetPayload<{
    include: {
      profile: true;
      _count: { select: { posts: true } };
    };
  }> {
  verificationLevel: VLevel;
  accountType: AType;
}

@Injectable()
export class AdminService {
  constructor(
    @Inject(PrismaService) private readonly prisma: PrismaService,
    @Inject(EmailService) private readonly emailService: EmailService,
    @Inject(NotificationsService)
    private readonly notificationsService: NotificationsService,
    @Inject(CACHE_MANAGER) private cacheManager: Cache,
  ) {}

  // ─── Audit Log Helper ─────────────────────────────────────────────

  /** Log every admin action for accountability. */
  async logAction(
    adminId: string,
    action: AdminAction,
    targetType: string,
    targetId: string,
    details?: string,
  ) {
    await this.prisma.adminAuditLog.create({
      data: { adminId, action, targetType, targetId, details },
    });
  }

  /** Helper to invalidate a profile cache by userId. */
  private async invalidateProfileCache(userId: string) {
    try {
      const profile = await this.prisma.profile.findUnique({
        where: { userId },
        select: { username: true },
      });
      if (profile) {
        await this.cacheManager.del(`profile:${profile.username}`);
      }
    } catch (error) {
      console.error('Failed to invalidate cache:', error);
    }
  }

  // ─── Statistics ───────────────────────────────────────────────────

  /** Basic stats for backwards compatibility. */
  async getStats() {
    const [userCount, postCount, storyCount, activeReports] = await Promise.all(
      [
        this.prisma.user.count(),
        this.prisma.post.count(),
        this.prisma.story.count(),
        this.prisma.report.count({ where: { status: ReportStatus.PENDING } }),
      ],
    );

    return {
      users: userCount,
      posts: postCount,
      stories: storyCount,
      pendingReports: activeReports,
    };
  }

  /** Enhanced stats with growth percentages and engagement metrics. */
  async getEnhancedStats() {
    const now = new Date();
    const oneWeekAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
    const twoWeeksAgo = new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000);
    const oneDayAgo = new Date(now.getTime() - 24 * 60 * 60 * 1000);

    const [
      totalUsers,
      totalPosts,
      totalStories,
      pendingReports,
      totalReports,
      newUsersThisWeek,
      newUsersLastWeek,
      newPostsThisWeek,
      newPostsLastWeek,
      totalLikes,
      totalComments,
      activeUsersToday,
    ] = await Promise.all([
      this.prisma.user.count(),
      this.prisma.post.count(),
      this.prisma.story.count(),
      this.prisma.report.count({ where: { status: ReportStatus.PENDING } }),
      this.prisma.report.count(),
      this.prisma.user.count({
        where: { createdAt: { gte: oneWeekAgo } },
      }),
      this.prisma.user.count({
        where: { createdAt: { gte: twoWeeksAgo, lt: oneWeekAgo } },
      }),
      this.prisma.post.count({
        where: { createdAt: { gte: oneWeekAgo } },
      }),
      this.prisma.post.count({
        where: { createdAt: { gte: twoWeeksAgo, lt: oneWeekAgo } },
      }),
      this.prisma.like.count(),
      this.prisma.comment.count(),
      this.prisma.user.count({
        where: {
          OR: [
            { isOnline: true },
            {
              lastSeenAt: {
                gte: oneDayAgo,
              },
            },
          ],
        },
      }),
    ]);

    // Fetch recent audit logs
    const recentAuditLogs = await this.prisma.adminAuditLog.findMany({
      take: 10,
      orderBy: { createdAt: 'desc' },
      include: {
        admin: {
          include: { profile: { select: { username: true } } },
        },
      },
    });

    const calcGrowth = (current: number, previous: number) => {
      if (previous === 0) return current > 0 ? 100 : 0;
      return Math.round(((current - previous) / previous) * 100);
    };

    return {
      users: totalUsers,
      posts: totalPosts,
      stories: totalStories,
      pendingReports,
      newUsersThisWeek,
      userGrowth: calcGrowth(newUsersThisWeek, newUsersLastWeek),
      newPostsThisWeek,
      postGrowth: calcGrowth(newPostsThisWeek, newPostsLastWeek),
      engagement:
        totalPosts > 0
          ? Math.round(((totalLikes + totalComments) / totalPosts) * 100) / 100
          : 0,
      reportedContentPercent:
        totalPosts > 0
          ? Math.round((totalReports / totalPosts) * 10000) / 100
          : 0,
      activeUsersToday,
      recentActivity: (recentAuditLogs ?? []).map((log) => ({
        id: log.id,
        action: log.action,
        targetType: log.targetType,
        targetId: log.targetId,
        details: log.details,
        createdAt: log.createdAt,
        adminUsername: log.admin?.profile?.username || 'Unknown',
      })),
    };
  }

  /**
   * Sends a premium broadcast email to all active users.
   * Processes users in batches of 25 to ensure system stability and avoid Brevo rate limits.
   */
  async sendBroadcastEmail(adminId: string, dto: BroadcastEmailDto) {
    // 1. Get all active users
    const activeUsers = await this.prisma.user.findMany({
      where: { isActive: true },
      select: { email: true, id: true },
    });

    if (activeUsers.length === 0) {
      return { success: true, recipients: 0, sent: 0, failed: 0 };
    }

    const batchSize = 25;
    let successfulSent = 0;
    let failedSent = 0;

    // 2. Process in batches to avoid blocking and respect Brevo constraints
    for (let i = 0; i < activeUsers.length; i += batchSize) {
      const batch = activeUsers.slice(i, i + batchSize);

      const results = await Promise.allSettled(
        batch.map((user) =>
          this.emailService.sendBroadcastEmail(
            user.email,
            dto.subject,
            dto.title,
            dto.content,
            dto.buttonText,
            dto.buttonUrl,
          ),
        ),
      );

      for (const result of results) {
        if (result.status === 'fulfilled') {
          successfulSent++;
        } else {
          failedSent++;
        }
      }
    }

    // 3. Log the audit action
    await this.logAction(
      adminId,
      AdminAction.UPDATE_WHITELIST,
      'NEWSLETTER',
      'GLOBAL',
      `Subject: ${dto.subject} | Success: ${successfulSent} | Failed: ${failedSent}`,
    );

    return {
      success: true,
      recipients: activeUsers.length,
      sent: successfulSent,
      failed: failedSent,
    };
  }

  // ─── Users ────────────────────────────────────────────────────────

  /** Paginated users with optional search and status filter. Includes role and post count. */
  async getUsers(page = 1, limit = 10, search?: string, status?: string) {
    const skip = (page - 1) * limit;
    const where: Prisma.UserWhereInput = {};

    if (search) {
      where.OR = [
        { email: { contains: search, mode: 'insensitive' } },
        {
          profile: {
            username: { contains: search, mode: 'insensitive' },
          },
        },
        {
          profile: {
            fullName: { contains: search, mode: 'insensitive' },
          },
        },
      ];
    }

    if (status === 'active') where.isActive = true;
    if (status === 'banned') where.isActive = false;

    const [users, total] = await Promise.all([
      this.prisma.user.findMany({
        where,
        skip,
        take: limit,
        orderBy: { createdAt: 'desc' },
        include: {
          profile: true,
          _count: { select: { posts: true } },
        },
      }),
      this.prisma.user.count({ where }),
    ]);

    return {
      data: (users as unknown as UserWithVerification[]).map((u) => ({
        id: u.id,
        email: u.email,
        isActive: u.isActive,
        role: u.role,
        verificationLevel: u.verificationLevel,
        accountType: u.accountType,
        createdAt: u.createdAt,
        profile: u.profile,
        postCount: u._count.posts,
      })),
      meta: {
        total,
        page,
        limit,
        totalPages: Math.ceil(total / limit),
      },
    };
  }

  /** Ban a user, with audit logging. */
  async banUser(adminId: string, userId: string) {
    const result = await this.prisma.user.update({
      where: { id: userId },
      data: { isActive: false },
      include: { profile: true },
    });
    await this.logAction(adminId, AdminAction.BAN_USER, 'user', userId);
    await this.invalidateProfileCache(userId);

    // Notify user via email
    if (result.email) {
      await this.emailService.sendModerationEmail(
        result.email,
        result.profile?.fullName || result.profile?.username || 'Usuario',
        'suspendida',
        'Cuenta',
        'Violación de los Términos de Servicio',
      );
    }

    return result;
  }

  /** Unban a user, with audit logging. */
  async unbanUser(adminId: string, userId: string) {
    const result = await this.prisma.user.update({
      where: { id: userId },
      data: { isActive: true },
    });
    await this.logAction(adminId, AdminAction.UNBAN_USER, 'user', userId);
    await this.invalidateProfileCache(userId);
    return result;
  }

  /** Promote user to ADMIN, with audit logging. */
  async promoteUser(adminId: string, userId: string) {
    const result = await this.prisma.user.update({
      where: { id: userId },
      data: { role: 'ADMIN' },
    });
    await this.logAction(adminId, AdminAction.PROMOTE_USER, 'user', userId);
    await this.invalidateProfileCache(userId);
    return result;
  }

  /** Demote user to USER, with audit logging. */
  async demoteUser(adminId: string, userId: string) {
    const result = await this.prisma.user.update({
      where: { id: userId },
      data: { role: 'USER' },
    });
    await this.logAction(adminId, AdminAction.DEMOTE_USER, 'user', userId);
    await this.invalidateProfileCache(userId);
    return result;
  }

  /** Update user verification level, account type, or activation status. */
  async updateUserStatus(
    adminId: string,
    userId: string,
    data: {
      verificationLevel?: string;
      accountType?: string;
      isActive?: boolean;
      role?: string;
    },
  ) {
    const updateData: Record<string, string | boolean | undefined> = {
      isActive: data.isActive,
      role: data.role,
    };

    if (data.verificationLevel) {
      updateData.verificationLevel = data.verificationLevel;
    }
    if (data.accountType) {
      updateData.accountType = data.accountType;
    }

    const result = await this.prisma.user.update({
      where: { id: userId },
      data: updateData as unknown as Prisma.UserUpdateInput,
    });
    await this.logAction(
      adminId,
      AdminAction.UPDATE_USER_STATUS,
      'user',
      userId,
      `Nivel: ${data.verificationLevel || 'n/a'}, Tipo: ${
        data.accountType || 'n/a'
      }`,
    );
    await this.invalidateProfileCache(userId);
    return result;
  }

  /** Hard-delete a user (cascades all data), with audit logging. */
  async deleteUser(adminId: string, userId: string) {
    await this.logAction(
      adminId,
      AdminAction.DELETE_USER,
      'user',
      userId,
      'Full account deletion',
    );
    return this.prisma.user.delete({ where: { id: userId } });
  }

  /** Paginated whitelist entries with optional search. */
  async getWhitelist(page = 1, limit = 10, search?: string) {
    const skip = (page - 1) * limit;
    const where: Prisma.WhitelistEntryWhereInput = {};

    if (search) {
      where.OR = [
        { email: { contains: search, mode: 'insensitive' } },
        { name: { contains: search, mode: 'insensitive' } },
      ];
    }

    const [entries, total] = await Promise.all([
      this.prisma.whitelistEntry.findMany({
        where,
        skip,
        take: limit,
        orderBy: { createdAt: 'desc' },
      }),
      this.prisma.whitelistEntry.count({ where }),
    ]);

    return {
      data: entries,
      meta: {
        total,
        page,
        limit,
        totalPages: Math.ceil(total / limit),
      },
    };
  }

  /** Update a whitelist entry status or details, with audit logging. */
  async updateWhitelist(
    adminId: string,
    id: string,
    data: UpdateWhitelistEntryDto,
  ) {
    const result = await this.prisma.whitelistEntry.update({
      where: { id },
      data: data as Prisma.WhitelistEntryUpdateInput,
    });
    await this.logAction(
      adminId,
      AdminAction.UPDATE_WHITELIST,
      'whitelist',
      id,
      JSON.stringify(data),
    );
    return result;
  }

  /** Delete a whitelist entry, with audit logging. */
  async deleteWhitelist(adminId: string, id: string) {
    await this.logAction(
      adminId,
      AdminAction.DELETE_WHITELIST,
      'whitelist',
      id,
    );
    return this.prisma.whitelistEntry.delete({ where: { id } });
  }

  // ─── Posts ────────────────────────────────────────────────────────

  /** Paginated posts with optional search and type filter. */
  async getPosts(page = 1, limit = 10, search?: string, type?: string) {
    const skip = (page - 1) * limit;
    const where: Prisma.PostWhereInput = {};

    if (search) {
      where.OR = [
        { caption: { contains: search, mode: 'insensitive' } },
        {
          user: {
            profile: {
              username: { contains: search, mode: 'insensitive' },
            },
          },
        },
      ];
    }

    if (type === 'POST' || type === 'FRAME') {
      where.type = type;
    }

    const [posts, total] = await Promise.all([
      this.prisma.post.findMany({
        where,
        skip,
        take: limit,
        orderBy: { createdAt: 'desc' },
        include: {
          user: { include: { profile: true } },
          media: true,
          _count: { select: { likes: true, comments: true } },
        },
      }),
      this.prisma.post.count({ where }),
    ]);

    return {
      data: posts,
      meta: {
        total,
        page,
        limit,
        totalPages: Math.ceil(total / limit),
      },
    };
  }

  /** Delete a post with audit logging. */
  async deletePost(adminId: string, postId: string) {
    await this.logAction(adminId, AdminAction.DELETE_POST, 'post', postId);
    const deletedPost = await this.prisma.post.delete({
      where: { id: postId },
      include: { user: { include: { profile: true } } },
    });

    if (deletedPost.user?.email) {
      await this.emailService.sendModerationEmail(
        deletedPost.user.email,
        deletedPost.user.profile?.username || 'Usuario',
        'eliminada',
        'Publicación',
        'Incumplimiento de nuestras políticas de contenido',
      );
    }

    return deletedPost;
  }

  // ─── Reports ──────────────────────────────────────────────────────

  /** Paginated reports with optional search and status filter. */
  async getReports(page = 1, limit = 10, search?: string, status?: string) {
    const skip = (page - 1) * limit;
    const where: Prisma.ReportWhereInput = {};

    if (
      status &&
      ['PENDING', 'RESOLVED', 'DISMISSED', 'REVIEWING'].includes(status)
    ) {
      where.status = status as ReportStatus;
    }

    if (search) {
      const isReason = Object.values(ReportReason).includes(
        search.toUpperCase() as ReportReason,
      );

      where.OR = [
        ...(isReason ? [{ reason: search.toUpperCase() as ReportReason }] : []),
        { details: { contains: search, mode: 'insensitive' } },
        {
          reporter: {
            profile: {
              username: { contains: search, mode: 'insensitive' },
            },
          },
        },
      ];
    }

    const [reports, total] = await Promise.all([
      this.prisma.report.findMany({
        where,
        skip,
        take: limit,
        orderBy: { createdAt: 'desc' },
        include: {
          reporter: {
            include: {
              profile: {
                select: { username: true, avatar: true },
              },
            },
          },
        },
      }),
      this.prisma.report.count({ where }),
    ]);

    // Enrich reports with target content details
    const enriched = await Promise.all(
      reports.map(async (report) => {
        let targetContent: {
          thumbnail?: string | null;
          text?: string | null;
          type?: string;
          author?: string;
        } | null = null;

        try {
          if (report.targetType === 'POST') {
            const post = await this.prisma.post.findUnique({
              where: { id: report.targetId },
              select: {
                caption: true,
                type: true,
                media: { take: 1, select: { url: true } },
                user: { select: { profile: { select: { username: true } } } },
              },
            });
            if (post) {
              targetContent = {
                thumbnail: post.media?.[0]?.url || null,
                text: post.caption,
                type: post.type,
                author: post.user?.profile?.username,
              };
            }
          } else if (report.targetType === 'STORY') {
            const story = await this.prisma.story.findUnique({
              where: { id: report.targetId },
              select: {
                url: true,
                mediaType: true,
                user: { select: { profile: { select: { username: true } } } },
              },
            });
            if (story) {
              targetContent = {
                thumbnail: story.url,
                text: null,
                type: 'STORY',
                author: story.user?.profile?.username,
              };
            }
          } else if (report.targetType === 'COMMENT') {
            const comment = await this.prisma.comment.findUnique({
              where: { id: report.targetId },
              select: {
                content: true,
                url: true,
                user: { select: { profile: { select: { username: true } } } },
              },
            });
            if (comment) {
              targetContent = {
                thumbnail: comment.url || null,
                text: comment.content,
                type: 'COMMENT',
                author: comment.user?.profile?.username,
              };
            }
          }
        } catch (err) {
          console.error(
            `Error fetching report target ${report.targetId}:`,
            err,
          );
        }

        return { ...report, targetContent };
      }),
    );

    return {
      data: enriched,
      meta: {
        total,
        page,
        limit,
        totalPages: Math.ceil(total / limit),
      },
    };
  }

  /** Update report status with audit logging. */
  async updateReportStatus(
    adminId: string,
    reportId: string,
    status: ReportStatus,
  ) {
    const result = await this.prisma.report.update({
      where: { id: reportId },
      data: { status },
    });
    const action =
      status === ReportStatus.RESOLVED
        ? AdminAction.REPORT_RESOLVED
        : AdminAction.REPORT_DISMISSED;
    await this.logAction(adminId, action, 'report', reportId);
    return result;
  }

  // ─── Audit Logs ───────────────────────────────────────────────────

  /** Paginated audit logs for admin accountability. */
  async getAuditLogs(page = 1, limit = 20) {
    const skip = (page - 1) * limit;

    const [logs, total] = await Promise.all([
      this.prisma.adminAuditLog.findMany({
        skip,
        take: limit,
        orderBy: { createdAt: 'desc' },
        include: {
          admin: {
            include: { profile: { select: { username: true } } },
          },
        },
      }),
      this.prisma.adminAuditLog.count(),
    ]);

    return {
      data: (logs ?? []).map((log) => ({
        id: log.id,
        action: log.action,
        targetType: log.targetType,
        targetId: log.targetId,
        details: log.details,
        createdAt: log.createdAt,
        adminUsername: log.admin?.profile?.username || 'Unknown',
      })),
      meta: {
        total,
        page,
        limit,
        totalPages: Math.ceil(total / limit),
      },
    };
  }

  // ─── CSV Export ───────────────────────────────────────────────────

  /** Export all users as CSV. */
  async exportUsersCSV() {
    const users = await this.prisma.user.findMany({
      orderBy: { createdAt: 'desc' },
      include: {
        profile: true,
        _count: { select: { posts: true } },
      },
    });

    const header = 'ID,Username,Email,Full Name,Role,Status,Posts,Joined';
    const rows = users.map((u) =>
      [
        u.id,
        u.profile?.username || '',
        u.email,
        `"${(u.profile?.fullName || '').replace(/"/g, '""')}"`,
        u.role,
        u.isActive ? 'Active' : 'Banned',
        u._count.posts,
        u.createdAt.toISOString(),
      ].join(','),
    );

    return [header, ...rows].join('\n');
  }

  /** Export all posts as CSV. */
  async exportPostsCSV() {
    const posts = await this.prisma.post.findMany({
      orderBy: { createdAt: 'desc' },
      include: {
        user: {
          include: { profile: { select: { username: true } } },
        },
        _count: { select: { likes: true, comments: true } },
      },
    });

    const header = 'ID,Author,Type,Caption,Likes,Comments,Created';
    const rows = posts.map((p) =>
      [
        p.id,
        p.user?.profile?.username || '',
        p.type,
        `"${(p.caption || '').replace(/"/g, '""').replace(/\n/g, ' ')}"`,
        p._count.likes,
        p._count.comments,
        p.createdAt.toISOString(),
      ].join(','),
    );

    return [header, ...rows].join('\n');
  }

  // ─── Activity Chart (last 14 days) ──────────────────────────────

  /** Posts and new users grouped by day for the last 14 days. */
  async getActivityChart() {
    const since = new Date();
    since.setDate(since.getDate() - 13);
    since.setHours(0, 0, 0, 0);

    const [posts, users] = await Promise.all([
      this.prisma.post.findMany({
        where: { createdAt: { gte: since } },
        select: { createdAt: true },
      }),
      this.prisma.user.findMany({
        where: { createdAt: { gte: since } },
        select: { createdAt: true },
      }),
    ]);

    // Build 14-day map
    const days: { date: string; posts: number; users: number }[] = [];
    for (let i = 0; i < 14; i++) {
      const d = new Date(since);
      d.setDate(d.getDate() + i);
      days.push({ date: d.toISOString().slice(0, 10), posts: 0, users: 0 });
    }

    for (const p of posts) {
      const key = p.createdAt.toISOString().slice(0, 10);
      const entry = days.find((d) => d.date === key);
      if (entry) entry.posts++;
    }
    for (const u of users) {
      const key = u.createdAt.toISOString().slice(0, 10);
      const entry = days.find((d) => d.date === key);
      if (entry) entry.users++;
    }

    return days;
  }

  // ─── Hashtags ───────────────────────────────────────────────────

  /** Paginated hashtags sorted by postCount desc. */
  async getHashtags(page = 1, limit = 20, search?: string) {
    const where: Prisma.HashtagWhereInput = search
      ? { tag: { contains: search, mode: 'insensitive' as const } }
      : {};

    const [data, total] = await Promise.all([
      this.prisma.hashtag.findMany({
        where,
        orderBy: { postCount: 'desc' },
        skip: (page - 1) * limit,
        take: limit,
      }),
      this.prisma.hashtag.count({ where }),
    ]);

    return {
      data,
      meta: { total, page, limit, totalPages: Math.ceil(total / limit) },
    };
  }

  // ─── Comments ──────────────────────────────────────────────────

  /** Paginated comments with author + post info. */
  async getComments(page = 1, limit = 10, search?: string) {
    const where: Prisma.CommentWhereInput = search
      ? { content: { contains: search, mode: 'insensitive' as const } }
      : {};

    const [data, total] = await Promise.all([
      this.prisma.comment.findMany({
        where,
        orderBy: { createdAt: 'desc' },
        skip: (page - 1) * limit,
        take: limit,
        include: {
          user: {
            select: { profile: { select: { username: true, avatar: true } } },
          },
          post: { select: { id: true, caption: true } },
        },
      }),
      this.prisma.comment.count({ where }),
    ]);

    return {
      data,
      meta: { total, page, limit, totalPages: Math.ceil(total / limit) },
    };
  }

  /** Delete a comment with audit logging. */
  async deleteComment(adminId: string, commentId: string) {
    await this.prisma.comment.delete({ where: { id: commentId } });
    await this.logAction(
      adminId,
      AdminAction.DELETE_COMMENT,
      'comment',
      commentId,
    );
  }

  // ─── Stories ───────────────────────────────────────────────────

  /** Paginated stories with view counts. */
  async getStories(page = 1, limit = 10) {
    const [data, total] = await Promise.all([
      this.prisma.story.findMany({
        orderBy: { createdAt: 'desc' },
        skip: (page - 1) * limit,
        take: limit,
        include: {
          user: {
            select: { profile: { select: { username: true, avatar: true } } },
          },
          _count: { select: { views: true, reactions: true } },
        },
      }),
      this.prisma.story.count(),
    ]);

    return {
      data,
      meta: { total, page, limit, totalPages: Math.ceil(total / limit) },
    };
  }

  /** Delete a story with audit logging. */
  async deleteStory(adminId: string, storyId: string) {
    await this.prisma.story.delete({ where: { id: storyId } });
    await this.logAction(adminId, AdminAction.DELETE_STORY, 'story', storyId);
  }

  // ─── User Detail ──────────────────────────────────────────────

  /** Enriched user info with follower counts, recent posts, and reports. */
  async getUserDetail(userId: string) {
    const user = await this.prisma.user.findUniqueOrThrow({
      where: { id: userId },
      include: {
        profile: true,
        posts: {
          orderBy: { createdAt: 'desc' },
          take: 5,
          select: { id: true, caption: true, createdAt: true, type: true },
        },
        reports: {
          orderBy: { createdAt: 'desc' },
          take: 5,
          select: { id: true, reason: true, status: true, createdAt: true },
        },
        _count: {
          select: {
            posts: true,
            followers: true,
            following: true,
          },
        },
      },
    });

    return user;
  }

  // ─── Top Users by Engagement ──────────────────────────────────

  /** Top 5 users by total likes + comments received on their posts. */
  async getTopUsers() {
    const users = await this.prisma.user.findMany({
      where: { isActive: true },
      select: {
        id: true,
        profile: { select: { username: true, avatar: true, fullName: true } },
        posts: {
          select: {
            _count: { select: { likes: true, comments: true } },
          },
        },
      },
    });

    const ranked = users
      .map((u) => {
        const totalLikes = u.posts.reduce((sum, p) => sum + p._count.likes, 0);
        const totalComments = u.posts.reduce(
          (sum, p) => sum + p._count.comments,
          0,
        );
        return {
          id: u.id,
          username: u.profile?.username || 'unknown',
          avatar: u.profile?.avatar,
          fullName: u.profile?.fullName,
          totalLikes,
          totalComments,
          engagement: totalLikes + totalComments,
        };
      })
      .sort((a, b) => b.engagement - a.engagement)
      .slice(0, 5);

    return ranked;
  }

  // ─── Analytics ───────────────────────────────────────────────────

  /** Return global monetization analytics (SaaS MRR) */
  async getMonetizationAnalytics(): Promise<Record<string, unknown>> {
    // Define a local interface to satisfy the business logic without depending
    // on Prisma's auto-generated types which are failing to export in the Alpine container.
    interface SubscriptionWithPlan {
      id: string;
      status: string;
      planId: string;
      plan: {
        id: string;
        name: string;
        price: number;
      };
    }

    // Use a structural cast to satisfy the Linter while allowing access to the model.
    const prisma = this.prisma as unknown as {
      platformSubscription: {
        findMany(args: {
          where?: Record<string, unknown>;
          include?: Record<string, boolean>;
        }): Promise<SubscriptionWithPlan[]>;
      };
    };

    const rawSubscriptions = await prisma.platformSubscription.findMany({
      where: { status: 'active' },
      include: { plan: true },
    });

    let activeMRR = 0;
    const tierCounts: Record<string, number> = {
      PREMIUM: 0,
      ELITE: 0,
      BUSINESS: 0,
    };

    rawSubscriptions.forEach((sub) => {
      activeMRR += sub.plan?.price || 0;
      // Map to consistent tier names
      const planName = sub.plan?.name?.toUpperCase() || '';
      if (planName.includes('PREMIUM')) tierCounts.PREMIUM++;
      else if (planName.includes('ELITE')) tierCounts.ELITE++;
      else if (planName.includes('BUSINESS')) tierCounts.BUSINESS++;
    });

    // Calculate subscription growth (last 30 days vs previous 30 days)
    const thirtyDaysAgo = new Date();
    thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);
    const sixtyDaysAgo = new Date();
    sixtyDaysAgo.setDate(sixtyDaysAgo.getDate() - 60);

    const [recentSubs, olderSubs] = await Promise.all([
      this.prisma.platformSubscription.count({
        where: {
          status: 'ACTIVE',
          createdAt: { gte: thirtyDaysAgo },
        },
      }),
      this.prisma.platformSubscription.count({
        where: {
          status: 'ACTIVE',
          createdAt: { gte: sixtyDaysAgo, lt: thirtyDaysAgo },
        },
      }),
    ]);

    let subscriptionGrowth = 0;
    if (olderSubs > 0) {
      subscriptionGrowth = Math.round(
        ((recentSubs - olderSubs) / olderSubs) * 100,
      );
    } else if (recentSubs > 0) {
      subscriptionGrowth = 100;
    }

    return {
      activeMRR,
      totalSubscriptions: rawSubscriptions.length,
      tierDistribution: tierCounts,
      subscriptionGrowth,
      activeRetentionRate: 98.5, // Stable benchmark for MVP
    };
  }

  // ─── Moderation Management ────────────────────────────────────────

  /**
   * Get a list of content (Posts, Stories, Comments) that is FLAGGED or HIDDEN.
   */
  async getModerationQueue(
    page = 1,
    limit = 10,
    targetType?: string,
    search?: string,
  ) {
    const skip = (page - 1) * limit;
    const whereClause: any = {
      moderationStatus: { in: ['FLAGGED', 'HIDDEN'] },
    };

    if (targetType) {
      // Logic could be expanded to query different models based on type
    }

    if (search) {
      whereClause.OR = [
        { caption: { contains: search, mode: 'insensitive' } },
        {
          user: {
            profile: {
              username: { contains: search, mode: 'insensitive' },
            },
          },
        },
      ];
    }

    const [posts, total] = await Promise.all([
      this.prisma.post.findMany({
        where: whereClause,
        skip,
        take: limit,
        orderBy: { updatedAt: 'desc' },
        include: {
          user: { include: { profile: true } },
          media: true,
        },
      }),
      this.prisma.post.count({ where: whereClause }),
    ]);

    return {
      data: posts,
      meta: {
        total,
        page,
        limit,
        totalPages: Math.ceil(total / limit),
      },
    };
  }

  /**
   * Update the moderation status of a piece of content.
   */
  async updateModerationStatus(
    adminId: string,
    targetType: 'POST' | 'STORY' | 'COMMENT',
    targetId: string,
    status: 'VISIBLE' | 'HIDDEN' | 'REMOVED',
    note?: string,
  ) {
    if (!['POST', 'STORY', 'COMMENT'].includes(targetType)) {
      throw new BadRequestException(`Invalid targetType: ${targetType}`);
    }
    if (!['VISIBLE', 'HIDDEN', 'REMOVED'].includes(status)) {
      throw new BadRequestException(`Invalid status: ${status}`);
    }

    const data = {
      moderationStatus: status as $Enums.ModerationStatus,
      moderationNote: note,
    };

    let result: any;
    if (targetType === 'POST') {
      result = await this.prisma.post.update({ where: { id: targetId }, data });
    } else if (targetType === 'STORY') {
      result = await this.prisma.story.update({
        where: { id: targetId },
        data,
      });
    } else if (targetType === 'COMMENT') {
      result = await this.prisma.comment.update({
        where: { id: targetId },
        data,
      });
    }

    const action =
      status === 'VISIBLE'
        ? ('CONTENT_RESTORED' as any as AdminAction)
        : status === 'HIDDEN'
          ? AdminAction.CONTENT_RESTRICTED
          : AdminAction.CONTENT_REMOVED;

    await this.logAction(
      adminId,
      action,
      targetType.toLowerCase(),
      targetId,
      note,
    );

    return result;
  }

  // ─── Promotions ─────────────────────────────────────────────────

  /**
   * Paginated list of promotions with target details.
   */
  async getPromotions(
    page = 1,
    limit = 10,
    status?: PromotionStatus,
    search?: string,
  ) {
    const skip = (page - 1) * limit;

    const where: Prisma.PromotionWhereInput = {};
    if (status) where.status = status as any;
    if (search) {
      where.user = {
        OR: [
          { email: { contains: search, mode: 'insensitive' } },
          { profile: { username: { contains: search, mode: 'insensitive' } } },
        ],
      };
    }

    const [promotions, total] = await Promise.all([
      this.prisma.promotion.findMany({
        where,
        skip,
        take: limit,
        orderBy: { createdAt: 'desc' },
        include: {
          user: {
            include: { profile: true },
          },
        },
      }),
      this.prisma.promotion.count({ where }),
    ]);

    // Resolve targets (Posts/Stories)
    const enrichedPromotions = await Promise.all(
      promotions.map(async (promo) => {
        let target: any = null;
        if (promo.targetType === 'POST') {
          target = await this.prisma.post.findUnique({
            where: { id: promo.targetId },
            include: { media: true },
          });
        } else if (promo.targetType === 'STORY') {
          target = await this.prisma.story.findUnique({
            where: { id: promo.targetId },
          });
        }
        return { ...promo, target };
      }),
    );

    return {
      data: enrichedPromotions,
      meta: {
        total,
        page,
        limit,
        totalPages: Math.ceil(total / limit),
      },
    };
  }

  /**
   * Update promotion status (Approve/Reject).
   */
  async updatePromotionStatus(
    adminId: string,
    promotionId: string,
    status: PromotionStatus,
    note?: string,
  ) {
    const promo = await this.prisma.promotion.findUnique({
      where: { id: promotionId },
    });

    if (!promo) {
      throw new NotFoundException('Promotion not found');
    }

    const updated = await this.prisma.promotion.update({
      where: { id: promotionId },
      data: { status: status as any },
    });

    await this.logAction(
      adminId,
      status === PromotionStatus.ACTIVE
        ? AdminAction.UPDATE_USER_STATUS
        : AdminAction.DELETE_POST,
      'promotion',
      promotionId,
      `Status changed to ${status}${note ? `: ${note}` : ''}`,
    );

    // 4. Notify the user
    await this.notificationsService.create({
      recipientId: promo.userId,
      senderId: adminId,
      type: NotificationType.MODERATION,
      content:
        status === PromotionStatus.ACTIVE
          ? `¡Tu promoción ha sido aprobada! Tu contenido ahora llegará a más personas.`
          : `Tu solicitud de promoción ha sido rechazada.${
              note ? ` Motivo: ${note}` : ''
            }`,
      postId: promo.targetType === 'POST' ? promo.targetId : undefined,
    });

    return updated;
  }
}
