export enum ErrorCode {
  // General Errors
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN_ACCESS = 'FORBIDDEN_ACCESS',
  INVALID_INPUT = 'INVALID_INPUT',

  // Users / Profiles
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  REPORT_NOT_FOUND = 'REPORT_NOT_FOUND',
  PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND',
  CANNOT_FOLLOW_SELF = 'CANNOT_FOLLOW_SELF',
  CANNOT_BLOCK_SELF = 'CANNOT_BLOCK_SELF',
  CANNOT_MUTE_SELF = 'CANNOT_MUTE_SELF',
  FOLLOW_REQUEST_NOT_FOUND = 'FOLLOW_REQUEST_NOT_FOUND',

  // Monetization & Payments
  INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS',
  CANNOT_BUY_OWN_CONTENT = 'CANNOT_BUY_OWN_CONTENT',
  CONTENT_ALREADY_UNLOCKED = 'CONTENT_ALREADY_UNLOCKED',
  NOT_PREMIUM_OR_NO_PRICE = 'NOT_PREMIUM_OR_NO_PRICE',
  BUYER_NOT_FOUND = 'BUYER_NOT_FOUND',
  SENDER_NOT_FOUND = 'SENDER_NOT_FOUND',
  MINIMUM_TIP_NOT_MET = 'MINIMUM_TIP_NOT_MET',
  CANNOT_TIP_SELF = 'CANNOT_TIP_SELF',
  STRIPE_CONNECT_NOT_SETUP = 'STRIPE_CONNECT_NOT_SETUP',
  CREATOR_STRIPE_NOT_SETUP = 'CREATOR_STRIPE_NOT_SETUP',
  STRIPE_ONBOARDING_FAILED = 'STRIPE_ONBOARDING_FAILED',
  PLAN_NOT_FOUND = 'PLAN_NOT_FOUND',
  PRICE_NOT_FOUND = 'PRICE_NOT_FOUND',
  ACTIVE_SUBSCRIPTION_EXISTS = 'ACTIVE_SUBSCRIPTION_EXISTS',
  STRIPE_CUSTOMER_MISSING = 'STRIPE_CUSTOMER_MISSING',
  PROMOTION_ID_MISSING = 'PROMOTION_ID_MISSING',

  // Posts & Media
  POST_NOT_FOUND = 'POST_NOT_FOUND',
  STORY_NOT_FOUND = 'STORY_NOT_FOUND',
  MEDIA_NOT_FOUND = 'MEDIA_NOT_FOUND',
  COMMENT_NOT_FOUND = 'COMMENT_NOT_FOUND',
  MESSAGE_NOT_FOUND = 'MESSAGE_NOT_FOUND',
  INVALID_MEDIA_PATH = 'INVALID_MEDIA_PATH',
  PREMIUM_CONTENT_LOCKED = 'PREMIUM_CONTENT_LOCKED',

  // Collections & Highlights
  COLLECTION_NOT_FOUND = 'COLLECTION_NOT_FOUND',
  HIGHLIGHT_NOT_FOUND = 'HIGHLIGHT_NOT_FOUND',
  EDIT_PROJECT_NOT_FOUND = 'EDIT_PROJECT_NOT_FOUND',

  // Interactive (Polls, QnA)
  INTERACTIVE_NOT_FOUND = 'INTERACTIVE_NOT_FOUND',
  MISSING_POST_OR_STORY_ID = 'MISSING_POST_OR_STORY_ID',
  POLL_ALREADY_EXISTS = 'POLL_ALREADY_EXISTS',
  QNA_ALREADY_EXISTS = 'QNA_ALREADY_EXISTS',
  INVALID_POLL_OPTION = 'INVALID_POLL_OPTION',
  EMPTY_ANSWER_TEXT = 'EMPTY_ANSWER_TEXT',

  // Live Streams
  STREAM_NOT_FOUND = 'STREAM_NOT_FOUND',
  STREAM_NOT_ACTIVE = 'STREAM_NOT_ACTIVE',
  ONLY_HOST_CAN_INVITE = 'ONLY_HOST_CAN_INVITE',
  ONLY_HOST_CAN_REMOVE = 'ONLY_HOST_CAN_REMOVE',
  CANNOT_INVITE_SELF = 'CANNOT_INVITE_SELF',
  NOT_A_COHOST = 'NOT_A_COHOST',
  CANNOT_GIFT_SELF = 'CANNOT_GIFT_SELF',
  GIFT_NOT_FOUND = 'GIFT_NOT_FOUND',
  CANNOT_RECONNECT_GUEST = 'CANNOT_RECONNECT_GUEST',
}
