export enum ErrorCode {
  // General Errors
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN_ACCESS = 'FORBIDDEN_ACCESS',
  INVALID_INPUT = 'INVALID_INPUT',

  // Users / Profiles
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND',
  CANNOT_FOLLOW_SELF = 'CANNOT_FOLLOW_SELF',
  CANNOT_BLOCK_SELF = 'CANNOT_BLOCK_SELF',
  CANNOT_MUTE_SELF = 'CANNOT_MUTE_SELF',
  FOLLOW_REQUEST_NOT_FOUND = 'FOLLOW_REQUEST_NOT_FOUND',

  // Monetization & Payments
  INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS',
  CANNOT_BUY_OWN_CONTENT = 'CANNOT_BUY_OWN_CONTENT',
  CONTENT_ALREADY_UNLOCKED = 'CONTENT_ALREADY_UNLOCKED',
  NOT_PREMIUM_OR_NO_PRICE = 'NOT_PREMIUM_OR_NO_PRICE',
  BUYER_NOT_FOUND = 'BUYER_NOT_FOUND',
  SENDER_NOT_FOUND = 'SENDER_NOT_FOUND',
  MINIMUM_TIP_NOT_MET = 'MINIMUM_TIP_NOT_MET',
  CANNOT_TIP_SELF = 'CANNOT_TIP_SELF',
  STRIPE_CONNECT_NOT_SETUP = 'STRIPE_CONNECT_NOT_SETUP',
  CREATOR_STRIPE_NOT_SETUP = 'CREATOR_STRIPE_NOT_SETUP',
  STRIPE_ONBOARDING_FAILED = 'STRIPE_ONBOARDING_FAILED',

  // Posts & Media
  POST_NOT_FOUND = 'POST_NOT_FOUND',
  STORY_NOT_FOUND = 'STORY_NOT_FOUND',
  MEDIA_NOT_FOUND = 'MEDIA_NOT_FOUND',
  INVALID_MEDIA_PATH = 'INVALID_MEDIA_PATH',
  PREMIUM_CONTENT_LOCKED = 'PREMIUM_CONTENT_LOCKED',

  // Collections & Highlights
  COLLECTION_NOT_FOUND = 'COLLECTION_NOT_FOUND',
  HIGHLIGHT_NOT_FOUND = 'HIGHLIGHT_NOT_FOUND',

  // Interactive (Polls, QnA)
  INTERACTIVE_NOT_FOUND = 'INTERACTIVE_NOT_FOUND',
  MISSING_POST_OR_STORY_ID = 'MISSING_POST_OR_STORY_ID',
}
