export enum ApiErrorCode {
  ACCOUNT_SUSPENDED = 'ACCOUNT_SUSPENDED',
  ACCOUNT_BANNED = 'ACCOUNT_BANNED',
  TWO_FA_REQUIRED = '2FA_REQUIRED',
  MAINTENANCE_MODE = 'MAINTENANCE_MODE',
  REGISTRATION_CLOSED = 'REGISTRATION_CLOSED',
  INVITE_CODE_REQUIRED = 'INVITE_CODE_REQUIRED',
  CONTENT_POSTING_DISABLED = 'CONTENT_POSTING_DISABLED',
  LIVE_STREAMS_DISABLED = 'LIVE_STREAMS_DISABLED',
  EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
  CAPTCHA_FAILED = 'CAPTCHA_FAILED',
  CAPTCHA_REQUIRED = 'CAPTCHA_REQUIRED',
}
