export enum ReportStatus {
  PENDING = 'PENDING',
  RESOLVED = 'RESOLVED',
  DISMISSED = 'DISMISSED',
}

export enum PostType {
  POST = 'POST',
  FRAME = 'FRAME',
}

export enum NotificationType {
  LIKE = 'LIKE',
  COMMENT = 'COMMENT',
  FOLLOW = 'FOLLOW',
  FOLLOW_REQUEST = 'FOLLOW_REQUEST',
  FOLLOW_ACCEPTED = 'FOLLOW_ACCEPTED',
  MENTION = 'MENTION',
  COMMENT_LIKE = 'COMMENT_LIKE',
  MODERATION = 'MODERATION',
  SUBSCRIPTION = 'SUBSCRIPTION',
  MESSAGE = 'MESSAGE',
  REPLY_MESSAGE = 'REPLY_MESSAGE',
}

export enum ReportReason {
  SPAM = 'SPAM',
  HARASSMENT = 'HARASSMENT',
  INAPPROPRIATE = 'INAPPROPRIATE',
  ILLEGAL_CONTENT = 'ILLEGAL_CONTENT',
  HATE_SPEECH = 'HATE_SPEECH',
  SELF_HARM = 'SELF_HARM',
  OTHER = 'OTHER',
}

export enum ReportTargetType {
  USER = 'USER',
  POST = 'POST',
  STORY = 'STORY',
  COMMENT = 'COMMENT',
  MESSAGE = 'MESSAGE',
}
