-- AlterTable
ALTER TABLE "posts" ADD COLUMN     "loops" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "performanceScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "watchTime" INTEGER NOT NULL DEFAULT 0;
