import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, NetworkFirst } from 'workbox-strategies';

declare const self: any;

// Precache all assets generated by the build process
precacheAndRoute(self.__WB_MANIFEST);

// Cache images from Cloudinary and UI-Avatars (Cache First)
registerRoute(
  ({ url }) =>
    url.hostname === 'res.cloudinary.com' || url.hostname === 'ui-avatars.com',
  new CacheFirst({
    cacheName: 'image-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
      }),
    ],
  }),
);

// Cache API GET requests for feeds and profiles (Network First)
registerRoute(
  ({ url, request }) =>
    request.method === 'GET' && url.pathname.startsWith('/api/v1/'),
  new NetworkFirst({
    cacheName: 'api-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 24 * 60 * 60, // 24 hours
      }),
    ],
    networkTimeoutSeconds: 3, // Fallback to cache quickly on slow connections
  }),
);

// Handle push notifications
self.addEventListener('push', (event: any) => {
  if (!event.data) return;

  try {
    const payload = event.data.json();
    const { title, body, data } = payload;

    event.waitUntil(
      self.registration.showNotification(title || 'CircleSfera', {
        body: body || '',
        icon: '/icons/icon-192.png',
        badge: '/icons/icon-192.png',
        data: data || {},
        vibrate: [200, 100, 200],
        tag: data?.type || 'general',
        renotify: true,
      } as any),
    );
  } catch (err) {
    console.error('Push event error:', err);
  }
});

// Handle notification click
self.addEventListener('notificationclick', (event: any) => {
  event.notification.close();

  const urlToOpen = event.notification.data?.url || '/';

  event.waitUntil(
    self.clients
      .matchAll({ type: 'window', includeUncontrolled: true })
      .then((windowClients: any[]) => {
        // If a window is already open, focus it and navigate
        for (const client of windowClients) {
          if (client.url === urlToOpen && 'focus' in client) {
            return client.focus();
          }
        }
        // Otherwise, open a new window
        if (self.clients.openWindow) {
          return self.clients.openWindow(urlToOpen);
        }
      }),
  );
});
