import { precacheAndRoute } from 'workbox-precaching';

declare const self: any;

// Precache all assets generated by the build process
precacheAndRoute(self.__WB_MANIFEST);

// Handle push notifications
self.addEventListener('push', (event: any) => {
  if (!event.data) return;

  try {
    const payload = event.data.json();
    const { title, body, data } = payload;

    event.waitUntil(
      self.registration.showNotification(title || 'CircleSfera', {
        body: body || '',
        icon: '/icons/icon-192.png',
        badge: '/icons/icon-192.png',
        data: data || {},
        vibrate: [200, 100, 200],
        tag: data?.type || 'general',
        renotify: true,
      } as any),
    );
  } catch (err) {
    console.error('Push event error:', err);
  }
});

// Handle notification click
self.addEventListener('notificationclick', (event: any) => {
  event.notification.close();

  const urlToOpen = event.notification.data?.url || '/';

  event.waitUntil(
    self.clients
      .matchAll({ type: 'window', includeUncontrolled: true })
      .then((windowClients: any[]) => {
        // If a window is already open, focus it and navigate
        for (const client of windowClients) {
          if (client.url === urlToOpen && 'focus' in client) {
            return client.focus();
          }
        }
        // Otherwise, open a new window
        if (self.clients.openWindow) {
          return self.clients.openWindow(urlToOpen);
        }
      }),
  );
});
